import test from 'node:test'; import assert from 'node:assert/strict'; import { readFile } from 'node:fs/promises';
import { buildProcessTwin } from '../src/evidence/build-process-twin.mjs';
const json=async p=>JSON.parse(await readFile(new URL(p,import.meta.url),'utf8'));
const input=async()=>{const spec=await json('../fixtures/evidence/process-input.ap-exception.json');return {...spec,claims:await json('../fixtures/evidence/claims.ap-exception.json')}};
test('build preserves four views, contradiction, and zero execution authority',async()=>{const twin=buildProcessTwin(await input());assert.equal(twin.execution_authority,'NONE');assert.equal(twin.unresolved_contradictions.length,1);assert.deepEqual(twin.unresolved_contradictions[0].claim_ids,['claim-documented-route','claim-observed-route']);assert.deepEqual(twin.topological_order,['validate-mismatch','route-mismatch','create-draft-case']);assert.equal(new Set(twin.nodes.map(n=>n.view)).size,3);});
test('input ordering cannot change the twin subject',async()=>{const a=await input();const b=structuredClone(a);b.claims.reverse();b.nodes.reverse();b.edges.reverse();const ta=buildProcessTwin(a),tb=buildProcessTwin(b);assert.equal(ta.twin_digest,tb.twin_digest);assert.deepEqual(ta,tb);});
test('node cannot collapse a source claim into another view',async()=>{const x=await input();x.nodes.find(n=>n.node_id==='route-mismatch').view='DOCUMENTED';assert.throws(()=>buildProcessTwin(x),e=>e.code==='VIEW_COLLAPSE');});
test('uncontrolled ordering cycle is rejected',async()=>{const x=await input();x.edges.push({edge_id:'edge-draft-validate',from:'create-draft-case',to:'validate-mismatch',relation:'PRECEDES',condition:null,controlled_cycle_id:null});assert.throws(()=>buildProcessTwin(x),e=>e.code==='UNCONTROLLED_CYCLE');});
test('unknown claim reference is rejected',async()=>{const x=await input();x.nodes[0].source_claim_ids=['claim-missing'];assert.throws(()=>buildProcessTwin(x),e=>e.code==='UNKNOWN_CLAIM_REFERENCE');});
